from semantic_router import Route
from semantic_router.encoders import OpenAIEncoder
from semantic_router.layer import RouteLayer
from dotenv import load_dotenv
import os

load_dotenv()

os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
encoder = OpenAIEncoder()


# we could use this as a guide for our chatbot to avoid political conversations
politics = Route(
    name="politics",
    utterances=[
        "isn't politics the best thing ever",
        "why don't you tell me about your political opinions",
        "don't you just love the president" "don't you just hate the president",
        "they're going to destroy this country!",
        "they will save the country!",
        "do you support war ?",
        "nazi",
        "israel",
        "palestine",
        "trump",
        "biden",
        "obama",
        "democrat",
        "republican",
        "war",
        "election",
        "racism",
        "sexism",
        "homophobia",
        "transphobia",
        "fascism",
        "communism",
        "socialism",
        "terrorism",
    ],
)

#Classique conversation with Lucy

chitchat = Route(
    name="chitchat",
    utterances=[
        "What's your favorite book?",
        "Any pets at home?",
        "Got any interesting hobbies?",
        "Heard any good jokes lately?",
        "Where's your dream vacation spot?",
        "Been anywhere exciting recently?",
        "Got a favorite sport you follow?",
        "Play any instruments?",
        "Binge-watching any good shows?",
        "What's your go-to season?",
        "Big family or small family?",
        "Ever met a really unusual animal?",
        "Cooking anything fun these days?",
        "Favorite dish to eat out?",
        "Coffee or tea person?",
        "Reading anything good?",
        "Prefer action or comedy movies?",
        "Hit the dance floor often?",
        "Go-to drink at a party?",
        "Got a quote that inspires you?",
        "Garden looking good this year?",
        "If you could have any job, what would it be?",
        "Swim much in the summer?",
        "Ice cream or cake?",
        "Ever tried painting?",
        "Favorite kind of flower?",
        "Cat person or dog person?",
        "What's on your playlist?",
        "Hit any trails recently?",
        "Best fruit for a summer day?",
        "Camping: love it or hate it?",
        "What's the best dessert you've ever had?",
        "Any favorite video games?",
        "Outdoor activities you enjoy?",
        "Puzzle master or not so much?",
        "Board games: yay or nay?",
        "Sing in the shower?",
        "Read any comics?",
        "Follow any sports teams?",
        "Morning person or night owl?",
        "Ever picked up photography?",
        "Best childhood memory?",
        "Ever tried knitting?",
        "Best place to unwind?",
        "Fishing fan?",
        "Dream car?",
        "Written anything lately?",
        "Favorite dance move?",
        "Yoga enthusiast?",
        "Rainy day activities?",
        "Good at chess?",
        "Snack of choice?",
        "Ever stargazed?",
        "A quote you love?",
        "Crafty projects lately?",
        "Best holiday ever?",
        "Cycling adventures?",
        "Favorite movie character?",
        "Beach or mountains?",
        "All-time favorite song?",
        "Run often?",
        "Superpower you wish you had?",
        "Favorite museum?",
        "TV character you relate to?",
        "Picnic plans?",
        "Ultimate video game?",
        "Baked anything good?",
        "Planet you'd visit?",
        "Bird watching trips?",
        "Historical figure you admire?",
        "Collect anything cool?",
        "Pet names?",
        "Roller skating fan?",
        "Fantasy world you'd live in?",
        "Ever performed magic tricks?",
        "Mythological creature you'd meet?",
        "Horseback riding ever?",
        "Sci-fi movie you'd recommend?",
        "Riddles or puzzles?",
        "Best mystery book?",
        "Explored any new places?",
        "Adventure you want to try?",
        "Handmade gifts: yes or no?",
        "Favorite superhero?",
        "Gardening tips?",
        "Tech gadget you love?",
        "Road trip memories?",
        "Favorite festival?",
        "Built anything recently?",
        "Space mission you're excited about?",
        "Wildlife encounters?",
        "Comic strip you read?",
        "DIY project successes?",
        "Dance style you like?",
        "Cartoons you watched as a kid?",
        "Favorite fairy tale?",
        "Card games: what's your favorite?",
        "Dessert recipe you swear by?",
        "Learning any new languages?",
        "Perfect Sunday plan?",
        "how's the weather today?",
        "how are things going?",
        "lovely weather today",
        "the weather is horrendous",
        "let's go to the chippy",
        "what is your name",
        "How are you?",
        "What is your favorite color?",
        "What is your favorite food?",
        "What is your favorite movie?",
        "are we friends?",
        "what is your favorite song?",
        "do you love me?",
        "let's be friends",
        "What's your favorite book?",
        "Do you like pets?",
        "Do you have any hobbies?",
        "Tell me a joke.",
        "What's your favorite holiday destination?",
        "Do you like to travel?",
        "What's your favorite sport?",
        "Do you play any musical instruments?",
        "What's your favorite TV show?",
        "What's your favorite season?",
        "Do you have any siblings?",
        "What's your favorite animal?",
        "Do you like to cook?",
        "What's your favorite cuisine?",
        "Do you prefer tea or coffee?",
        "Do you enjoy reading?",
        "What's your favorite movie genre?",
        "Do you like to dance?",
        "What's your favorite drink?",
        "Do you have a favorite quote?",
        "Do you enjoy gardening?",
        "What's your dream job?",
        "Do you like to swim?",
        "What's your favorite ice cream flavor?",
        "Do you like to paint?",
        "What's your favorite flower?",
        "Do you prefer cats or dogs?",
        "What's your favorite type of music?",
        "Do you like to hike?",
        "What's your favorite fruit?",
        "Do you enjoy camping?",
        "What's your favorite dessert?",
        "Do you like to play video games?",
        "What's your favorite outdoor activity?",
        "Do you enjoy puzzles?",
        "What's your favorite board game?",
        "Do you like to sing?",
        "What's your favorite comic book?",
        "Do you like to watch sports?",
        "What's your favorite time of day?",
        "Do you enjoy photography?",
        "What's your favorite childhood memory?",
        "Do you like to knit?",
        "What's your favorite place to relax?",
        "Do you enjoy fishing?",
        "What's your favorite car?",
        "Do you like to write?",
        "What's your favorite dance style?",
        "Do you enjoy yoga?",
        "What's your favorite thing to do on a rainy day?",
        "Do you like to play chess?",
        "What's your favorite snack?",
        "Do you enjoy stargazing?",
        "What's your favorite quote?",
        "Do you like to do crafts?",
        "What's your favorite holiday?",
        "Do you enjoy cycling?",
        "What's your favorite movie character?",
        "Do you like to go to the beach?",
        "What's your favorite song?",
        "Do you enjoy running?",
        "What's your favorite superpower?",
        "Do you like to visit museums?",
        "What's your favorite TV character?",
        "Do you enjoy picnics?",
        "What's your favorite video game?",
        "Do you like to bake?",
        "What's your favorite planet?",
        "Do you enjoy bird watching?",
        "What's your favorite historical period?",
        "Do you like to collect anything?",
        "What's your favorite pet's name?",
        "Do you enjoy roller skating?",
        "What's your favorite fantasy world?",
        "Do you like to do magic tricks?",
        "What's your favorite mythological creature?",
        "Do you enjoy horseback riding?",
        "What's your favorite science fiction movie?",
        "Do you like to solve riddles?",
        "What's your favorite mystery book?",
        "Do you enjoy exploring new places?",
        "What's your favorite adventure?",
        "Do you like to make handmade gifts?",
        "What's your favorite superhero?",
        "Do you enjoy gardening?",
        "What's your favorite tech gadget?",
        "Do you like to go on road trips?",
        "What's your favorite festival?",
        "Do you enjoy building models?",
        "What's your favorite space mission?",
        "Do you like to watch wildlife?",
        "What's your favorite comic strip?",
        "Do you enjoy DIY projects?",
        "What's your favorite type of dance?",
        "Do you like to watch cartoons?",
        "What's your favorite fairy tale?",
        "Do you enjoy playing cards?",
        "What's your favorite dessert recipe?",
        "Do you like to learn new languages?",
        "What's your favorite way to spend a Sunday?"
    ],
)


# we place both of our decisions together into single list
routes = [chitchat]


rl = RouteLayer(encoder=encoder, routes=routes)