from semantic_router import Route
from semantic_router.encoders import OpenAIEncoder
from semantic_router.layer import RouteLayer
from dotenv import load_dotenv
import os

load_dotenv()

os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
encoder = OpenAIEncoder()


# we could use this as a guide for our chatbot to avoid political conversations
politics = Route(
    name="politics",
    utterances=[
        "isn't politics the best thing ever",
        "why don't you tell me about your political opinions",
        "don't you just love the president" "don't you just hate the president",
        "they're going to destroy this country!",
        "they will save the country!",
        "do you support war ?",
        "nazi",
        "israel",
        "palestine",
        "trump",
        "biden",
        "obama",
        "democrat",
        "republican",
        "war",
        "election",
        "racism",
        "sexism",
        "homophobia",
        "transphobia",
        "fascism",
        "communism",
        "socialism",
        "terrorism",
    ],
)

#Classique conversation with Lucy
chitchat = Route(
    name="chitchat",
    utterances=[
        "how's the weather today?",
        "how are things going?",
        "lovely weather today",
        "the weather is horrendous",
        "let's go to the chippy",
        "what is your name",
        "How are you?",
        "What is your favorite color?",
        "What is your favorite food?",
        "What is your favorite movie?",
        "are we friends?",
        "what is your favorite song?",
        "do you love me?",
        "let's be friends",
    ],
)



# Route for selecting or switching a major
major_selection = Route(
    name="major_selection",
    utterances=[
        "What major should I choose?",
        "Can you help me select a major?",
        "I'm undecided about my major.",
        "What are the best majors for job prospects?",
        "What is the most popular major?",
        "How do I know if a major is right for me?",
        "Can I switch my major?",
        "How do I change my major?",
        "Is it too late to switch majors?",
        "What are the steps to change my major?",
        "What should I consider when choosing a major?",
        "Can you tell me about different majors?",
        "Which majors are best for a career in technology?",
        "What major should I choose if I want to be a doctor?",
        "How do I decide between two m ajors?",
        "What majors are available at this university?",
        "Can I double major?",
        "How does double majoring work?",
        "What is the process to declare a major?",
        "What are the requirements for changing majors?",
        "Is there a deadline to switch majors?",
        "Can I switch my major after my first year?",
        "How can I explore different majors?",
        "Can I talk to an advisor about selecting a major?",
        "What major should I choose for a career in finance?",
        "How can I find out more about specific majors?",
        "Can I switch majors if I'm not doing well in my current one?",
        "How do I plan my courses if I switch majors?",
        "Can switching majors affect my graduation date?",
        "What are the pros and cons of switching majors?",
        "How do I choose a major based on my interests?",
        "Can you suggest some majors for someone interested in art?",
        "What are some interdisciplinary majors?",
        "What is a major declaration form?",
        "Can I switch my major multiple times?",
        "What impact does changing majors have on my transcript?",
        "Can switching majors affect my financial aid?",
        "How do I discuss changing majors with my parents?",
    ],
)

# Route for identifying difficulty or serious problems
# Route for identifying difficulty, distress, or need for guidance and help
problem = Route(
    name="problem",
    utterances=[
        "I'm struggling with my studies.",
        "I can't keep up with my coursework.",
        "I'm having a hard time understanding the material.",
        "I feel overwhelmed by my classes.",
        "I think I'm going to fail my exams.",
        "I'm falling behind in my assignments.",
        "I don't know how to manage my time.",
        "I'm stressed out about my grades.",
        "I'm not doing well in school.",
        "I need help with my homework.",
        "I'm worried about failing a class.",
        "I can't focus on my studies.",
        "I'm experiencing a lot of stress.",
        "I'm feeling anxious about school.",
        "I need support with my academics.",
        "I'm having trouble with a specific subject.",
        "I'm finding it hard to balance school and life.",
        "I don't understand the lectures.",
        "I'm considering dropping out.",
        "I'm struggling with mental health issues.",
        "I feel depressed.",
        "I'm not sure if I can continue with my studies.",
        "I'm dealing with personal problems.",
        "I can't concentrate in class.",
        "I'm having problems with my teachers.",
        "I feel like I'm not smart enough.",
        "I'm struggling with procrastination.",
        "I don't know how to study effectively.",
        "I'm feeling isolated.",
        "I'm not motivated to study.",
        "I'm having trouble with my roommates.",
        "I feel lonely.",
        "I'm dealing with family issues.",
        "I don't feel safe on campus.",
        "I'm being bullied.",
        "I need someone to talk to.",
        "I'm having financial difficulties.",
        "I can't afford my textbooks.",
        "I'm worried about my future.",
        "I feel like giving up.",
        "I'm experiencing burnout.",
        "I need academic counseling.",
        "I'm facing discrimination.",
        "I'm struggling with substance abuse.",
        "I'm worried about my health.",
        "I feel hopeless.",
        "I'm not eating well.",
        "I'm not sleeping well.",
        "I need help with exam preparation.",
        "I can't handle the pressure.",
        "I'm feeling lost.",
        "I need guidance on how to improve my grades.",
        "I'm afraid of failing.",
        "I'm having issues with time management.",
        "I'm stressed about choosing a major.",
        "I'm feeling unmotivated.",
        "I need advice on how to cope with stress.",
        "I'm feeling overwhelmed with responsibilities.",
        "I need help finding resources for support.",
        "I'm worried about my mental well-being.",
        "I'm not enjoying my studies.",
        "I feel disconnected from my peers.",
        "Can you recommend any mental health services?",
        "Where can I find counseling services?",
        "How can I contact a mental health professional?",
        "I need help with mental health resources.",
        "Can you provide information on stress management workshops?",
        "Are there any support groups on campus?",
        "How do I access student health services?",
        "Who can I talk to about my mental health?",
        "Where can I find resources for dealing with anxiety?",
        "How do I make an appointment with a counselor?",
        "Are there any helplines I can call?",
        "What should I do if I'm feeling overwhelmed?",
        "Can you give me the contact for student support services?",
        "Where can I get help for depression?",
        "Are there any mental health resources available for students?",
        "I need to speak with someone about my stress levels.",
        "How do I find a therapist?",
        "Can you guide me to mental health support?",
        "What are the emergency mental health contacts?",
        "Where can I get help for substance abuse?",
        "I need advice on managing my mental health.",
    ],
)
# we place both of our decisions together into single list
routes = [politics, chitchat, problem, major_selection]


rl = RouteLayer(encoder=encoder, routes=routes)