from semantic_router import Route
from semantic_router.encoders import OpenAIEncoder
from semantic_router.layer import RouteLayer
from dotenv import load_dotenv
import os

load_dotenv()

os.environ['OPENAI_API_KEY'] = os.getenv('OPENAI_API_KEY')
encoder = OpenAIEncoder()


# we could use this as a guide for our chatbot to avoid political conversations
politics = Route(
    name="politics",
    utterances=[
        "isn't politics the best thing ever",
        "why don't you tell me about your political opinions",
        "don't you just love the president" "don't you just hate the president",
        "they're going to destroy this country!",
        "they will save the country!",
        "do you support war ?",
        "nazi",
        "israel",
        "palestine",
        "trump",
        "biden",
        "obama",
        "democrat",
        "republican",
        "war",
        "election",
        "racism",
        "sexism",
        "homophobia",
        "transphobia",
        "fascism",
        "communism",
        "socialism",
        "terrorism",
    ],
)

chitchat = Route(
    name="chitchat",
    utterances=[
        "What's your favorite book?",
        "Any pets at home?",
        "Got any interesting hobbies?",
        "Heard any good jokes lately?",
        "Where's your dream vacation spot?",
        "Been anywhere exciting recently?",
        "Got a favorite sport you follow?",
        "Play any instruments?",
        "Binge-watching any good shows?",
        "What's your go-to season?",
        "Big family or small family?",
        "Ever met a really unusual animal?",
        "Cooking anything fun these days?",
        "Favorite dish to eat out?",
        "Coffee or tea person?",
        "Reading anything good?",
        "Prefer action or comedy movies?",
        "Hit the dance floor often?",
        "Go-to drink at a party?",
        "Got a quote that inspires you?",
        "Garden looking good this year?",
        "If you could have any job, what would it be?",
        "Swim much in the summer?",
        "Ice cream or cake?",
        "Ever tried painting?",
        "Favorite kind of flower?",
        "Cat person or dog person?",
        "What's on your playlist?",
        "Hit any trails recently?",
        "Best fruit for a summer day?",
        "Camping: love it or hate it?",
        "What's the best dessert you've ever had?",
        "Any favorite video games?",
        "Outdoor activities you enjoy?",
        "Puzzle master or not so much?",
        "Board games: yay or nay?",
        "Sing in the shower?",
        "Read any comics?",
        "Follow any sports teams?",
        "Morning person or night owl?",
        "Ever picked up photography?",
        "Best childhood memory?",
        "Ever tried knitting?",
        "Best place to unwind?",
        "Fishing fan?",
        "Dream car?",
        "Written anything lately?",
        "Favorite dance move?",
        "Yoga enthusiast?",
        "Rainy day activities?",
        "Good at chess?",
        "Snack of choice?",
        "Ever stargazed?",
        "A quote you love?",
        "Crafty projects lately?",
        "Best holiday ever?",
        "Cycling adventures?",
        "Favorite movie character?",
        "Beach or mountains?",
        "All-time favorite song?",
        "Run often?",
        "Superpower you wish you had?",
        "Favorite museum?",
        "TV character you relate to?",
        "Picnic plans?",
        "Ultimate video game?",
        "Baked anything good?",
        "Planet you'd visit?",
        "Bird watching trips?",
        "Historical figure you admire?",
        "Collect anything cool?",
        "Pet names?",
        "Roller skating fan?",
        "Fantasy world you'd live in?",
        "Ever performed magic tricks?",
        "Mythological creature you'd meet?",
        "Horseback riding ever?",
        "Sci-fi movie you'd recommend?",
        "Riddles or puzzles?",
        "Best mystery book?",
        "Explored any new places?",
        "Adventure you want to try?",
        "Handmade gifts: yes or no?",
        "Favorite superhero?",
        "Gardening tips?",
        "Tech gadget you love?",
        "Road trip memories?",
        "Favorite festival?",
        "Built anything recently?",
        "Space mission you're excited about?",
        "Wildlife encounters?",
        "Comic strip you read?",
        "DIY project successes?",
        "Dance style you like?",
        "Cartoons you watched as a kid?",
        "Favorite fairy tale?",
        "Card games: what's your favorite?",
        "Dessert recipe you swear by?",
        "Learning any new languages?",
        "Perfect Sunday plan?",
        "how's the weather today?",
        "how are things going?",
        "lovely weather today",
        "the weather is horrendous",
        "let's go to the chippy",
        "what is your name",
        "How are you?",
        "What is your favorite color?",
        "What is your favorite food?",
        "What is your favorite movie?",
        "are we friends?",
        "what is your favorite song?",
        "do you love me?",
        "let's be friends",
        "What's your favorite book?",
        "Do you like pets?",
        "Do you have any hobbies?",
        "Tell me a joke.",
        "What's your favorite holiday destination?",
        "Do you like to travel?",
        "What's your favorite sport?",
        "Do you play any musical instruments?",
        "What's your favorite TV show?",
        "What's your favorite season?",
        "Do you have any siblings?",
        "What's your favorite animal?",
        "Do you like to cook?",
        "What's your favorite cuisine?",
        "Do you prefer tea or coffee?",
        "Do you enjoy reading?",
        "What's your favorite movie genre?",
        "Do you like to dance?",
        "What's your favorite drink?",
        "Do you have a favorite quote?",
        "Do you enjoy gardening?",
        "What's your dream job?",
        "Do you like to swim?",
        "What's your favorite ice cream flavor?",
        "Do you like to paint?",
        "What's your favorite flower?",
        "Do you prefer cats or dogs?",
        "What's your favorite type of music?",
        "Do you like to hike?",
        "What's your favorite fruit?",
        "Do you enjoy camping?",
        "What's your favorite dessert?",
        "Do you like to play video games?",
        "What's your favorite outdoor activity?",
        "Do you enjoy puzzles?",
        "What's your favorite board game?",
        "Do you like to sing?",
        "What's your favorite comic book?",
        "Do you like to watch sports?",
        "What's your favorite time of day?",
        "Do you enjoy photography?",
        "What's your favorite childhood memory?",
        "Do you like to knit?",
        "What's your favorite place to relax?",
        "Do you enjoy fishing?",
        "What's your favorite car?",
        "Do you like to write?",
        "What's your favorite dance style?",
        "Do you enjoy yoga?",
        "What's your favorite thing to do on a rainy day?",
        "Do you like to play chess?",
        "What's your favorite snack?",
        "Do you enjoy stargazing?",
        "What's your favorite quote?",
        "Do you like to do crafts?",
        "What's your favorite holiday?",
        "Do you enjoy cycling?",
        "What's your favorite movie character?",
        "Do you like to go to the beach?",
        "What's your favorite song?",
        "Do you enjoy running?",
        "What's your favorite superpower?",
        "Do you like to visit museums?",
        "What's your favorite TV character?",
        "Do you enjoy picnics?",
        "What's your favorite video game?",
        "Do you like to bake?",
        "What's your favorite planet?",
        "Do you enjoy bird watching?",
        "What's your favorite historical period?",
        "Do you like to collect anything?",
        "What's your favorite pet's name?",
        "Do you enjoy roller skating?",
        "What's your favorite fantasy world?",
        "Do you like to do magic tricks?",
        "What's your favorite mythological creature?",
        "Do you enjoy horseback riding?",
        "What's your favorite science fiction movie?",
        "Do you like to solve riddles?",
        "What's your favorite mystery book?",
        "Do you enjoy exploring new places?",
        "What's your favorite adventure?",
        "Do you like to make handmade gifts?",
        "What's your favorite superhero?",
        "Do you enjoy gardening?",
        "What's your favorite tech gadget?",
        "Do you like to go on road trips?",
        "What's your favorite festival?",
        "Do you enjoy building models?",
        "What's your favorite space mission?",
        "Do you like to watch wildlife?",
        "What's your favorite comic strip?",
        "Do you enjoy DIY projects?",
        "What's your favorite type of dance?",
        "Do you like to watch cartoons?",
        "What's your favorite fairy tale?",
        "Do you enjoy playing cards?",
        "What's your favorite dessert recipe?",
        "Do you like to learn new languages?",
        "What's your favorite way to spend a Sunday?"
    ],
)




# Route for selecting or switching a major
major_selection = Route(
    name="major_selection",
    utterances=[
        "What major should I choose?",
        "Can you help me select a major?",
        "I'm undecided about my major.",
        "What are the best majors for job prospects?",
        "What is the most popular major?",
        "How do I know if a major is right for me?",
        "Can I switch my major?",
        "How do I change my major?",
        "Is it too late to switch majors?",
        "What are the steps to change my major?",
        "What should I consider when choosing a major?",
        "Can you tell me about different majors?",
        "Which majors are best for a career in technology?",
        "What major should I choose if I want to be a doctor?",
        "How do I decide between two m ajors?",
        "What majors are available at this university?",
        "Can I double major?",
        "How does double majoring work?",
        "What is the process to declare a major?",
        "What are the requirements for changing majors?",
        "Is there a deadline to switch majors?",
        "Can I switch my major after my first year?",
        "How can I explore different majors?",
        "Can I talk to an advisor about selecting a major?",
        "What major should I choose for a career in finance?",
        "How can I find out more about specific majors?",
        "Can I switch majors if I'm not doing well in my current one?",
        "How do I plan my courses if I switch majors?",
        "Can switching majors affect my graduation date?",
        "What are the pros and cons of switching majors?",
        "How do I choose a major based on my interests?",
        "Can you suggest some majors for someone interested in art?",
        "What are some interdisciplinary majors?",
        "What is a major declaration form?",
        "Can I switch my major multiple times?",
        "What impact does changing majors have on my transcript?",
        "Can switching majors affect my financial aid?",
        "How do I discuss changing majors with my parents?",
    ],
)

# Route for identifying difficulty or serious problems
# Route for identifying difficulty, distress, or need for guidance and help
problem = Route(
    name="problem",
    utterances=[
        "I'm struggling with my studies.",
        "I can't keep up with my coursework.",
        "I'm having a hard time understanding the material.",
        "I feel overwhelmed by my classes.",
        "I think I'm going to fail my exams.",
        "I'm falling behind in my assignments.",
        "I don't know how to manage my time.",
        "I'm stressed out about my grades.",
        "I'm not doing well in school.",
        "I need help with my homework.",
        "I'm worried about failing a class.",
        "I can't focus on my studies.",
        "I'm experiencing a lot of stress.",
        "I'm feeling anxious about school.",
        "I need support with my academics.",
        "I'm having trouble with a specific subject.",
        "I'm finding it hard to balance school and life.",
        "I don't understand the lectures.",
        "I'm considering dropping out.",
        "I'm struggling with mental health issues.",
        "I feel depressed.",
        "I'm not sure if I can continue with my studies.",
        "I'm dealing with personal problems.",
        "I can't concentrate in class.",
        "I'm having problems with my teachers.",
        "I feel like I'm not smart enough.",
        "I'm struggling with procrastination.",
        "I don't know how to study effectively.",
        "I'm feeling isolated.",
        "I'm not motivated to study.",
        "I'm having trouble with my roommates.",
        "I feel lonely.",
        "I'm dealing with family issues.",
        "I don't feel safe on campus.",
        "I'm being bullied.",
        "I need someone to talk to.",
        "I'm having financial difficulties.",
        "I can't afford my textbooks.",
        "I'm worried about my future.",
        "I feel like giving up.",
        "I'm experiencing burnout.",
        "I need academic counseling.",
        "I'm facing discrimination.",
        "I'm struggling with substance abuse.",
        "I'm worried about my health.",
        "I feel hopeless.",
        "I'm not eating well.",
        "I'm not sleeping well.",
        "I need help with exam preparation.",
        "I can't handle the pressure.",
        "I'm feeling lost.",
        "I need guidance on how to improve my grades.",
        "I'm afraid of failing.",
        "I'm having issues with time management.",
        "I'm stressed about choosing a major.",
        "I'm feeling unmotivated.",
        "I need advice on how to cope with stress.",
        "I'm feeling overwhelmed with responsibilities.",
        "I need help finding resources for support.",
        "I'm worried about my mental well-being.",
        "I'm not enjoying my studies.",
        "I feel disconnected from my peers.",
        "Can you recommend any mental health services?",
        "Where can I find counseling services?",
        "How can I contact a mental health professional?",
        "I need help with mental health resources.",
        "Can you provide information on stress management workshops?",
        "Are there any support groups on campus?",
        "How do I access student health services?",
        "Who can I talk to about my mental health?",
        "Where can I find resources for dealing with anxiety?",
        "How do I make an appointment with a counselor?",
        "Are there any helplines I can call?",
        "What should I do if I'm feeling overwhelmed?",
        "Can you give me the contact for student support services?",
        "Where can I get help for depression?",
        "Are there any mental health resources available for students?",
        "I need to speak with someone about my stress levels.",
        "How do I find a therapist?",
        "Can you guide me to mental health support?",
        "What are the emergency mental health contacts?",
        "Where can I get help for substance abuse?",
        "I need advice on managing my mental health.",
    ],
)
# we place both of our decisions together into single list
routes = [chitchat]


rl = RouteLayer(encoder=encoder, routes=routes)